controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints: 
      - jRightKnee_roty
      - jLeftKnee_roty  
      - jRightHip_roty
      - jLeftHip_roty
    command_interfaces:
      - position
    state_interfaces:
      - position